### ISSUE TITLE
A few implementation references

### ISSUE THREAD

**Issue by frankobe** [bodhiproject/qweb3.js#1]
1. For model and monitoring
https://github.com/qtumproject/qtum-explorer

2. For rpc call
https://github.com/qtumproject/qtumcore-lib

3. Decode log based on event abi
 a. https://github.com/ConsenSys/abi-decoder/blob/ecbdc4dbbea9108953b340b3a89881a6b4232ecf/index.js#L101
 b.https://github.com/hayeah/qtumjs/blob/d7ebdbb1cc88a5e948ce6c08918d01a26a7964ed/src/abi.ts#L56-L91

**Comment by chrisli30** [comment]
Close it since I've starred and read all three. Marking it with enhancement label for later references.
