### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: JSON value is not a string as expected

### ISSUE THREAD

**Issue by raineroviir** [bodhiproject/qweb3.js#47]
I'm getting this 

```
UnhandledPromiseRejectionWarning: Error: JSON value is not a string as expected
```

for every single command that isn't a utility.  So that means my qtumd rpc is acting up.  Any ideas or advice?  I can make these commands with qtum-cli

**Comment by dwalintukan** [comment]
@raineroviir What command were you trying to execute? Can you give me a specific function call with the exact params you are sending in?

**Comment by dwalintukan** [comment]
Closing for now unless he responds with more info.
