### ISSUE TITLE
Error: Invalid Qtum address

### ISSUE THREAD

**Issue by dzarezenko** [bodhiproject/qweb3.js#66]
I am trying to convert Qtum address to hex...

```
const { Qweb3 } = require('qweb3');

const qClient = new Qweb3('http://user:pass@localhost:13889');

async function getHexAddress(address) {
  return await qClient.getHexAddress(address);
}

getHexAddress('qKjn4fStBaAtwGiwueJf9qFxgpbAvf1xAy').then(function(result) {
   console.log(result) //will log results.
});

getHexAddress('Qh1UygQTXB5PSdkEhHnqUXGAjmzGW5Rh2d').then(function(result) {
   console.log(result) //will log results.
});
```

but received this error:

```
17e7888aa7412a735f336d2f6d784caefabb6fa3
(node:8620) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid Qtum address
```

The 1st address is from this repository docs and it works, but 2nd one is my test address and I received `Invalid Qtum address` error. But this is [valid address ](https://explorer.qtum.org/address/Qh1UygQTXB5PSdkEhHnqUXGAjmzGW5Rh2d) .

What is wrong?

**Comment by dwalintukan** [comment]
@dzarezenko When you instantiated your `qClient`, you are passing in a testnet port. Meaning you started `qtumd` with the testnet flag. You can't use mainnet addresses on the testnet (`Qh1UygQTXB5PSdkEhHnqUXGAjmzGW5Rh2d` is a mainnet address).
